Draft Implementation of time integration class
Building-acoustics-TU-Eindhoven/edg-acoustics pull request #16
Opened 2023-12-03 16:43 UTC by hqwang815

2023-12-18 14:32 UTC, hqwang815 commented
Initial completion of the DG code.

2024-01-30 15:42 UTC, apalha requested changes
@hqwang815 , I finished reviewing and adding my comments. I propose you go over them and then we arrange a meeting and discuss this.

2024-01-31 09:37 UTC, hqwang815 commented on edg_acoustics/acoustics_simulation.py
> +    def __init__(self, rho0: float, c0: float, Nx: int, Nt: int, mesh: edg_acoustics.Mesh, BC_list: dict[str, int], node_tolerance: float = NODETOL):
Yes, I was wondering the same before. Now, I added as you suggested

2024-02-01 13:59 UTC, hqwang815 commented on edg_acoustics/acoustics_simulation.py
> +    def locate_simplex(node_coordinates: numpy.ndarray, node_ids: numpy.ndarray, rec: numpy.ndarray):
Thanks. I write it as a static method and explicitly pass `node coordinates`, `node_ids` in order to make it possible to call this function from another code, for example my colleague's code that needs the same function. Of course, we can make our own user's life easier. I will change it as you suggest and add the options.

2024-02-01 20:15 UTC, hqwang815 commented on edg_acoustics/acoustics_simulation.py
> +    def init_TimeIntegration(self, TI: edg_acoustics.TimeIntegrator, rec: numpy.ndarray, TotalTime: float=0.05):
Yes, i implement `init_rec` inside AcousticSimulation class and it takes `rec` as input.
In the future, we might need to add functionality to read input of text file later. I add this functionality in the issue to be solved. Let's just keep it simple for now.

2024-02-01 20:22 UTC, hqwang815 commented on edg_acoustics/acoustics_simulation.py
> +        nodeindex = tri.find_simplex(rec.T)
Yes, like I reply above. I will add two options.

2024-02-01 21:46 UTC, merged